### ISSUE TITLE
Wrapping Rust SDK using rustler

### ISSUE THREAD

**Issue by catethos** [maxohq/surrealix#4]
is it possible to wrap the Rust SDK using rustler? Since Rust SDK gets the official support and has the latest feature. I think the Python SDK is taking similar approach.

**Comment by mindreframer** [comment]
Yes, this might work. Since I do not have much of Rust experience myself and right now I'm not planning to invest much time into learning it, it wont happen on this project. Also, the API from the rust SDK is slightly different, it should be a separate, dedicated API client.
